/**
 * attachments.ts 的稳定公开入口。
 * 具体职责已拆分到同名子目录，调用方无需感知内部模块布局。
 */
export { AUTO_MODE_ATTACHMENT_CONFIG } from './attachment-pipeline/types.js'
export { collectRecentSuccessfulTools } from './attachment-pipeline/contextDelta.js'
export { collectSurfacedMemories } from './attachment-pipeline/contextDelta.js'
export { createAttachmentMessage } from './attachment-pipeline/memory.js'
export { extractAgentMentions } from './attachment-pipeline/contextDelta.js'
export { extractAtMentionedFiles } from './attachment-pipeline/contextDelta.js'
export { extractMcpResourceMentions } from './attachment-pipeline/contextDelta.js'
export { filterDuplicateMemoryAttachments } from './attachment-pipeline/contextDelta.js'
export { filterToBundledAndMcp } from './attachment-pipeline/contextDelta.js'
export { generateFileAttachment } from './attachment-pipeline/memory.js'
export { getAgentListingDeltaAttachment } from './attachment-pipeline/modeReminders.js'
export { getAgentPendingMessageAttachments } from './attachment-pipeline/collection.js'
export { getAttachmentMessages } from './attachment-pipeline/memory.js'
export { getAttachments } from './attachment-pipeline/collection.js'
export { getChangedFiles } from './attachment-pipeline/modeReminders.js'
export { getCompactionReminderAttachment } from './attachment-pipeline/skills.js'
export { getDateChangeAttachments } from './attachment-pipeline/collection.js'
export { getDeferredToolsDeltaAttachment } from './attachment-pipeline/modeReminders.js'
export { getDirectoriesToProcess } from './attachment-pipeline/modeReminders.js'
export { getMcpInstructionsDeltaAttachment } from './attachment-pipeline/modeReminders.js'
export { getQueuedCommandAttachments } from './attachment-pipeline/collection.js'
export { getVerifyPlanReminderTurnCount } from './attachment-pipeline/skills.js'
export { memoryFilesToAttachments } from './attachment-pipeline/modeReminders.js'
export { memoryHeader } from './attachment-pipeline/contextDelta.js'
export { parseAtMentionedFileLines } from './attachment-pipeline/contextDelta.js'
export { PLAN_MODE_ATTACHMENT_CONFIG } from './attachment-pipeline/types.js'
export { readMemoriesForSurfacing } from './attachment-pipeline/contextDelta.js'
export { RELEVANT_MEMORIES_CONFIG } from './attachment-pipeline/types.js'
export { resetSentSkillNames } from './attachment-pipeline/contextDelta.js'
export { startRelevantMemoryPrefetch } from './attachment-pipeline/contextDelta.js'
export { suppressNextSkillListing } from './attachment-pipeline/contextDelta.js'
export { TODO_REMINDER_CONFIG } from './attachment-pipeline/types.js'
export { tryGetPDFReference } from './attachment-pipeline/memory.js'
export { VERIFY_PLAN_REMINDER_CONFIG } from './attachment-pipeline/types.js'
export type { AgentMentionAttachment } from './attachment-pipeline/types.js'
export type { AlreadyReadFileAttachment } from './attachment-pipeline/types.js'
export type { AsyncHookResponseAttachment } from './attachment-pipeline/types.js'
export type { Attachment } from './attachment-pipeline/types.js'
export type { CompactFileReferenceAttachment } from './attachment-pipeline/types.js'
export type { FileAttachment } from './attachment-pipeline/types.js'
export type { HookAttachment } from './attachment-pipeline/types.js'
export type { HookCancelledAttachment } from './attachment-pipeline/types.js'
export type { HookErrorDuringExecutionAttachment } from './attachment-pipeline/types.js'
export type { HookNonBlockingErrorAttachment } from './attachment-pipeline/types.js'
export type { HookPermissionDecisionAttachment } from './attachment-pipeline/types.js'
export type { HookSuccessAttachment } from './attachment-pipeline/types.js'
export type { HookSystemMessageAttachment } from './attachment-pipeline/types.js'
export type { MemoryPrefetch } from './attachment-pipeline/contextDelta.js'
export type { PDFReferenceAttachment } from './attachment-pipeline/types.js'
export type { TeamContextAttachment } from './attachment-pipeline/types.js'
export type { TeammateMailboxAttachment } from './attachment-pipeline/types.js'
