/**
 * marketplaceManager.ts 的稳定公开入口。
 * 具体职责已拆分到同名子目录，调用方无需感知内部模块布局。
 */
export { _test } from './marketplace-manager/registry.js'
export { addMarketplaceSource } from './marketplace-manager/sourceCache.js'
export { clearMarketplacesCache } from './marketplace-manager/configuration.js'
export { getDeclaredMarketplaces } from './marketplace-manager/configuration.js'
export { getMarketplace } from './marketplace-manager/sourceCache.js'
export { getMarketplaceCacheOnly } from './marketplace-manager/sourceCache.js'
export { getMarketplaceDeclaringSource } from './marketplace-manager/configuration.js'
export { getMarketplacesCacheDir } from './marketplace-manager/configuration.js'
export { getPluginById } from './marketplace-manager/sourceCache.js'
export { getPluginByIdCacheOnly } from './marketplace-manager/sourceCache.js'
export { gitClone } from './marketplace-manager/gitTransport.js'
export { gitPull } from './marketplace-manager/configuration.js'
export { loadKnownMarketplacesConfig } from './marketplace-manager/configuration.js'
export { loadKnownMarketplacesConfigSafe } from './marketplace-manager/configuration.js'
export { reconcileSparseCheckout } from './marketplace-manager/gitTransport.js'
export { refreshAllMarketplaces } from './marketplace-manager/registry.js'
export { refreshMarketplace } from './marketplace-manager/registry.js'
export { registerSeedMarketplaces } from './marketplace-manager/configuration.js'
export { removeMarketplaceSource } from './marketplace-manager/sourceCache.js'
export { saveKnownMarketplacesConfig } from './marketplace-manager/configuration.js'
export { saveMarketplaceToSettings } from './marketplace-manager/configuration.js'
export { setMarketplaceAutoUpdate } from './marketplace-manager/registry.js'
export type { DeclaredMarketplace } from './marketplace-manager/configuration.js'
export type { KnownMarketplacesConfig } from './marketplace-manager/configuration.js'
export type { MarketplaceProgressCallback } from './marketplace-manager/gitTransport.js'
