/**
 * pluginLoader.ts 的稳定公开入口。
 * 具体职责已拆分到同名子目录，调用方无需感知内部模块布局。
 */
export { cachePlugin } from './plugin-loader/sourceInstallers.js'
export { cachePluginSettings } from './plugin-loader/marketplaceLoading.js'
export { clearPluginCache } from './plugin-loader/marketplaceLoading.js'
export { copyDir } from './plugin-loader/cachePaths.js'
export { copyPluginToVersionedCache } from './plugin-loader/cachePaths.js'
export { createPluginFromPath } from './plugin-loader/sourceInstallers.js'
export { generateTemporaryCacheNameForPlugin } from './plugin-loader/cachePaths.js'
export { getLegacyCachePath } from './plugin-loader/cachePaths.js'
export { getPluginCachePath } from './plugin-loader/cachePaths.js'
export { getVersionedCachePath } from './plugin-loader/cachePaths.js'
export { getVersionedCachePathIn } from './plugin-loader/cachePaths.js'
export { getVersionedZipCachePath } from './plugin-loader/cachePaths.js'
export { gitClone } from './plugin-loader/cachePaths.js'
export { installFromGitSubdir } from './plugin-loader/cachePaths.js'
export { installFromNpm } from './plugin-loader/cachePaths.js'
export { loadAllPlugins } from './plugin-loader/marketplaceLoading.js'
export { loadAllPluginsCacheOnly } from './plugin-loader/marketplaceLoading.js'
export { loadPluginManifest } from './plugin-loader/sourceInstallers.js'
export { mergePluginSources } from './plugin-loader/marketplaceLoading.js'
export { probeSeedCacheAnyVersion } from './plugin-loader/cachePaths.js'
export { resolvePluginPath } from './plugin-loader/cachePaths.js'
